# training loop hyp
wandb_log: true
wandb_group: time_jepa_lp
epochs: 30
wd: 0.1
batch_size: 96
patience: 30

lr_head: 0.001

linear_probing: true
deterministic: false

use_ecg_jepa: true

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/


training_pct: 1.
