# training loop hyp
wandb_log: true
wandb_group: time_xlstm_sup
epochs: 30
wd: 0.1
batch_size: 96
patience: 30

lr_head: 0.0001
lr_core: 0.0001
drop_path_prob: 0.
layerwise_lr_decay: 0. # 0.75

linear_probing: false
deterministic: false

embedding_size: 1024
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
# checkpoint: pretrain-xLSTM/0rgc8fun/checkpoints/epoch=49-step=504700.ckpt

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/


training_pct: 1.
