# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_lp
epochs: 30
wd: 0.001
batch_size: 256

lr_head: 0.1
lr_core: 0.1
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false

linear_probing: true
deterministic: false

use_ecg_cpc: true
data_folder_deepbeat: /scratch/datasets/DeepBeat_PPG
data_pct: 0.05
