!!python/object/new:utils.utils.ConfigDict
dictitems:
  activation_fn: gelu
  batch_size: 96
  bidirectional: true
  checkpoint: pretrained_models/simdino/transformer.ckpt
  clip_grad: 3.0
  cls_normalization: null
  cls_type: null
  data_folder_mit: /media/Volume/data/MIT-BHI/data/
  deterministic: false
  drop_path_prob: false
  dropout: 0.0
  embedding_size: 768
  encoder_type: transformer
  epochs: 30
  grad_clip: 0.5
  is_recurrent: false
  is_sweep: false
  layerwise_lr_decay: 0.0
  leads:
  - I
  - II
  - III
  - aVR
  - aVL
  - aVF
  - V1
  - V2
  - V3
  - V4
  - V5
  - V6
  linear_probing: true
  lr_head: 0.01
  lr_xlstm: 1.0e-05
  max_length_signal: 1000
  monitor_metric: val_f1
  monitor_mode: max
  n_global_view: 1
  n_local_view: 0
  nk_clean: false
  normalize: false
  num_classes: 25
  num_epochs_warmup: 1
  num_heads: 4
  num_reg_token: 0
  num_workers: 32
  optimizer: adamw
  original_freq: 360
  patch_embedding: non_linear
  patch_size: 25
  patience: 30
  plot_test_predictions: true
  r_peaks_detection: true
  random_change_amplitude: 0.0
  random_crop: 1.0
  random_drop_leads: 0.0
  random_jitter_prob: 0.0
  random_shift: false
  random_surrogate_prob: 0.0
  sampling_freq: 100
  sched_decay_factor: 0.8
  shift_baseline_wander_in_sample: false
  shuffle_baseline_wander_in_batch: false
  skip_majority_class_samples: false
  split_val_by_patient: true
  use_class_weights: true
  use_ecg_founder: false
  use_ecg_jepa: false
  use_final_layer_norm: true
  use_focal_loss: false
  use_scheduler: true
  use_st_mem: false
  wandb_group: transformer_lp
  wandb_log: true
  wd: 0.01
  win_len: 500
  window_size_train: 1000
  window_size_val: 1000
  xlstm_config:
  - s
  - s
  - m
  - m
  - s
  - s
  - m
  - m
  - s
