[project]
name = "bench-xecg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.15.1",
    "joblib>=1.5.3",
    "lightning>=2.6.1",
    "numpy>=2.4.2",
    "pandarallel>=1.6.5",
    "pandas>=3.0.1",
    "pathlib>=1.0.1",
    "torch>=2.10.0",
    "wfdb>=4.3.1",
    "xlstm>=2.0.5",
]
