wandb_log: true
wandb_group: best_ecgfm_ft

epochs: 30
lr_head: .01
lr_core: .001
wd: 0.1

linear_probing: false
deterministic: false

batch_size: 128
use_ecg_founder: true
use_st_mem: false
use_ecg_jepa: false

data_folder_deepbeat: /scratch/datasets/DeepBeat_PPG

num_workers: 64
data_pct: 0.05
