wandb_log: true
wandb_group: best_stmem_lp

epochs: 30
lr_head: .0003
lr_core: .0003
wd: 0.1

linear_probing: true
deterministic: false

batch_size: 128
use_st_mem: true

data_folder_deepbeat: /scratch/datasets/DeepBeat_PPG

num_workers: 64
data_pct: 0.05
