# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_lp
epochs: 30
wd: 0.001
batch_size: 256

lr_head: 0.1
lr_core: 0.01
discriminative_lr_factor: 0.1
precision: '32'

linear_probing: true
deterministic: false

use_ecg_cpc: true
split_signal: false

data_folder_ptbxl: /home/parikshit/datasets/ptbxl/physionet.org/files/ptb-xl/1.0.3/records500/


training_pct: 1.
normalize: true