# training loop hyp
wandb_log: true
wandb_group: best_ecgfm_ft_bis
epochs: 30
wd: 0.1
batch_size: 256

lr_head: 0.001
lr_core: 0.00001

use_ecg_founder: true

linear_probing: false
deterministic: false

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/


training_pct: 1.
