# training loop hyp
wandb_log: true
wandb_group: best_xlstm_ft_bis
epochs: 30
wd: 0.1
batch_size: 256

lr_head: 0.001
lr_core: 0.0003
drop_path_prob: 0.
layerwise_lr_decay: .75 #0.9 # 0.75

linear_probing: false
deterministic: false

embedding_size: 1024
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
checkpoint: pretrain-xLSTM/0rgc8fun/checkpoints/epoch=49-step=504700.ckpt

use_final_layer_norm: false
cls_normalization: 'batch'  # 'batch', 'layer', 'instance'
cls_type: avg

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/


random_paper_layout: 0.9
random_paper_6x2_prob: 0.8

classes: ['NORM', 'STTC', 'MI']
num_classes: 3

training_pct: 1.
optimizer: 'momentum'
use_scheduler: false