# training hyperparameters
epochs: 100
lr: 0.001
reconstruction_lr: 0.001
wd: 0.0001
dropout: 0.3
grad_clip: 0.5

# dataloaders
batch_size: 192
num_workers: 32
deterministic: true

# pretrain losses params
loss_type: mse_grad_min_max
grad_loss_lambda: 1.0
min_max_loss_lambda: 1.0

# optimize and scheduler
optimizer: adamw
use_scheduler: true
num_epochs_warmup: 2
num_epochs_warm_restart: 10
sched_decay_factor: 0.8
patience: 10

# model hyperparameters
patch_size: 32
embedding_size: 512
activation_fn: relu
xlstm_config: [ 'm', 's', 'm', 's', 'm', 's', 'm' ]
wandb_log: false
num_heads: 4
xlstm_type: original
weight_tying: false
patch_embedding: linear
bidirectional: false
strategy: next_token_prediction # masked_token_prediction
mask_ratio: 0.5 # only for masked_token_prediction
monitor_metric: val_nrmse
monitor_delay_epochs: 2


# jepa like args
use_teacher_student: false
ema_0: 0.996 
ema_1: 1.
n_prototypes: 65536
start_train_head_at_epoch: 0
use_koleo_regularization: false
centering: sinkhorn_knopp
teacher_temp: 0.07

# data and augmentations hyperparameters
normalize: true
nk_clean: true
shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: true
random_crop: 0.9
random_drop_leads: 0
random_surrogate_prob: 0
random_jitter_prob: 0
pretrain_datasets: ['code15', 'mimic', 'ptbxl']
leads: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

# dataset folders
data_folder_mit: /media/Volume/data/MIT-BHI/data/
name: 'static'
win_len: 1800
data_folder_code15: /media/Volume/data/CODE15/processed/
labels_file_code15: /media/Volume/data/CODE15/processed/exams_filtered.csv
data_folder_mimic: /media/Volume/data/MIMIC_IV/
labels_file_mimic: /media/Volume/data/MIMIC_IV/exams_filtered.csv
data_folder_ptbxl: /media/Volume/data/PTB-XL/records500/
labels_file_ptbxl: /media/Volume/data/PTB-XL/exams_filtered.csv

# other
debug: false

n_local_view: 6
n_global_view: 2

sampling_freq: 100
nk_clean: true
use_sim_dino: true