lr_head: 0.003
lr_xlstm: 0.00001
wd: 0.01
batch_size: 64
num_workers: 32
epochs: 30
patch_size: 128
dropout: 0.4
embedding_size: 512
deterministic: true
is_sweep: false
grad_clip: 0.5
weight_tying: false
label_smoothing: 0.0
num_classes: 9

optimizer: "adamw"
use_scheduler: true
num_epochs_warmup: 1
num_epochs_warm_restart: 15
sched_decay_factor: 0.8
random_surrogate_prob: 0.0
random_jitter_prob: 0.0
random_drop_leads: 0.0
random_change_amplitude: 0.
patience: 15
num_reg_token: 0
max_length_signal: 60

activation_fn: "relu"
xlstm_config: ["m", "s", "m", "m", "m", "m", "m"]
wandb_log: false
num_heads: 4
xlstm_type: "small"
patch_embedding: "linear"
bidirectional: false
use_cls_token: false
use_focal_loss: false
sampling_freq: 100
use_final_layer_norm: true


normalize: true
random_crop: 0.9
nk_clean: true
leads: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

data_folder_cpsc2018: /media/Volume/data/CPSC2018/
labels_file_cpsc2018: /media/Volume/data/CPSC2018/exams_filtered.csv

checkpoint: null
n_global_view: 1
n_local_view: 0