# training loop hyp
wandb_log: true
wandb_group: best_jepa_lp
epochs: 30
wd: 0.1
batch_size: 512

lr_head: 0.001

linear_probing: true
deterministic: false

use_ecg_jepa: true

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'
training_dataset: ['code15']
max_length_signal: 2500


data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/
labels_file_mimic: /scratch/datasets/mimic-iv-ecg/raw/exams_filtered.csv
data_folder_code15: /scratch/datasets/CODE15/processed/
labels_file_code15: /scratch/datasets/CODE15/processed/exams_filtered.csv