# training loop hyp
wandb_log: true
wandb_group: best_jepa_lp

lr_head: .001
wd: 0.1
linear_probing: true
deterministic: false
batch_size: 96
num_workers: 64

use_ecg_jepa: true

skip_majority_class_samples: true
use_class_weights: false
split_val_by_patient: true
win_len: 1250

data_folder_mit: /home/datasets/MIT-BIH_arrhythmia/