epochs: 100
dropout: 0.1
lr: 0.001
wd: 0.001
patch_size: 256
embedding_size: 1024
xlstm_config: [ 'm', 's', 'm', 's', 'm', 's', 'm' ]
xlstm_type: original

# no restarts
num_epochs_warm_restart: 100
num_epochs_warmup: 5
patience: 20

patch_embedding: enriched

loss_type: mse_grad_min_max
