epochs: 100
lr: 0.0003
wd: 0.0001
patch_size: 128
batch_size: 64
embedding_size: 1024
xlstm_config: [ 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm' ]
xlstm_type: vanilla
random_drop_leads: 0.4
dropout: 0.1
gradient_clipping: .5

# scheduler
use_scheduler: true
num_epochs_warm_restart: 10
num_epochs_warmup: 2
patience: 30

patch_embedding: enriched

loss_type: mse_grad_min_max
debug: true
bidirectional: true
wandb_log: true

data_folder_code15: "/scratch/datasets/CODE15/360hz_nkclean"
data_folder_mimic: "/scratch/datasets/mimic-iv-ecg/360hz_nkclean"
data_folder_mit: "/scratch/datasets/MIT-BIH_arrhythmia/raw"
data_folder_ptbxl: "/scratch/datasets/ptb-xl/nkclean_360_12l"

labels_file_code15: "/scratch/datasets/CODE15/360hz_nkclean/exams_labelled.csv"
labels_file_mimic: "/scratch/datasets/mimic-iv-ecg/360hz_nkclean/records_w_diag_icd10_labelled.csv"
labels_file_ptbxl: "/scratch/datasets/ptb-xl/nkclean_360_12l/ptbxl_database.csv"
