ptb_xl: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/ptb-xl/xlstm_lp.yaml
cpsc2018: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/cpsc2018/xlstm_lp.yaml
mit_bih: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/mit_bih_cls/xlstm_lp.yaml
r_peaks: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/mit_bih_r/xlstm_lp.yaml
exercise_r_peaks: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/exercise/xlstm_lp.yaml
sleep_apnea: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/sleep_apnea/xlstm_lp.yaml
ppg_af: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/deepbeat/xlstm_lp.yaml
age: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/age/xlstm_lp.yaml
lab_test: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/lab/xlstm_lp.yaml
survival: /home/q036rl/MIT-BIH_ecg_arrhytmia/configs/mortality/xlstm_lp.yaml