wandb_log: true
epochs: 30
lr_head: .001
lr_core: .00001
wd: 0.1
dropout: 0.
linear_probing: true
task: multiclass
deterministic: false

use_ecg_founder: false
use_st_mem: true
use_ecg_jepa: false

random_surrogate_prob: 0.
random_jitter_prob: 0.
random_drop_leads: 0.
random_resample: false
random_crop: 1. # 0.9
normalize: false
nk_clean: false

shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: false
random_change_amplitude: 0.

patch_size: 25
sampling_freq: 100
batch_size: 512
num_classes: 2
data_folder_deepbeat: /scratch/datasets/DeepBeat_PPG
patience: 5
drop_path_prob: 0.5 # 0.75
layerwise_lr_decay: 0.75 # 0.75

monitor_metric: val_auroc

# embedding_size: 768
embedding_size: 1024
# encoder_type: transformer
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
# xlstm_config: ['m','m','s','s','m','m','s','s','m','m','m']
checkpoint: pretrain-xLSTM/bjtcbcpo/checkpoints/epoch=50-step=656472.ckpt 
# checkpoint: pretrain-xLSTM/y7gvl8tt/checkpoints/epoch=10-step=117260.ckpt
# patch_embedding: non_linear
patch_embedding: linear
use_final_layer_norm: false
bidirectional: true
cls_type: avg
num_reg_token: 0
nk_clean: false
num_workers: 64
cls_normalization: null 
data_pct: 0.05
