wandb_log: true

lr_head: 0.001
lr_xlstm: 0.00001
wd: 0.001
dropout: 0.1
random_shift: true

embedding_size: 1024
xlstm_type: "vanilla"
xlstm_config: [ 'm', 's', 'm', 's', 'm', 's', 'm', 's', 'm' ]
checkpoint: pretrained_models/9l_1024/epoch=8-step=38070.ckpt
patch_embedding: enriched

patch_size: 64

use_scheduler: true
num_epochs_warm_restart: 30
patience: 30
batch_size: 128
optimizer: 'adamw'
use_cls_token: true
grad_clip: .5


classification_taksk: 'diagnosis_superclass'
num_classes: 5 # chenge to 23 if diagnosis_subclass