# training loop hyp
wandb_log: true
epochs: 50
lr_head: 0.001
lr_core: 0.00001
wd: 0.1
dropout: 0.
linear_probing: false
# max_length_signal: 60
deterministic: false

use_ecg_jepa: false
use_st_mem: false
use_ecg_founder: false

max_length_signal: 1000

#embedding_size: 1024
embedding_size: 768
xlstm_type: transformer
# xlstm_type: vanilla
# xlstm_config:  [ 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's']
# xlstm_config: ['m','m','s','s','m','m','s','s','m','m','m']
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
checkpoint: pretrain-xLSTM/y7gvl8tt/checkpoints/epoch=10-step=117260.ckpt
# checkpoint: pretrain-xLSTM/bjtcbcpo/checkpoints/epoch=50-step=656472.ckpt 
use_ecg_cpc: true

patch_size: 25
use_final_layer_norm: false
use_cls_normalization: batch
patch_embedding: non_linear
bidirectional: true
cls_type: max
task: multilabel
num_reg_token: 0

use_scheduler: true
num_epochs_warmup: 1
patience: 20
batch_size: 96
optimizer: 'adamw'
grad_clip: 3

# sampling_freq: 100
use_class_weights: true

random_surrogate_prob: 0.
random_jitter_prob: 0.
random_drop_leads: 0.
random_crop: 1. # 0.9
normalize: false
nk_clean: false
shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: false
random_change_amplitude: 0.

drop_path_prob: 0.5 #0.5
layerwise_lr_decay: 0.75  # 0.75
training_pct: 1.

data_folder_cpsc2018: /home/datasets/CPSC2018/
labels_file_cpsc2018: /home/datasets/CPSC2018/exams_filtered.csv
