# training loop hyp
wandb_log: false
wandb_group: test
epochs: 1
wd: 0.1
batch_size: 512

lr_head: 0.001

linear_probing: true
deterministic: true

use_ecg_founder: false

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

embedding_size: 1024
encoder_type: vanilla
# xlstm_config:  [ 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's', 's', 'm', 'm', 's']
xlstm_config: ["s","s","m","m","s", "s","m","m","s"]
checkpoint: pretrained_models/simdino/no_mimic_xlstm.ckpt
use_final_layer_norm: false
