wandb_log: true
epochs: 15
lr_head: 0.0001
lr_core: 0.0001
wd: 0.01
dropout: 0.
random_shift: false
normalize: false
linear_probing: false
deterministic: false

use_ecg_jepa: false
use_st_mem: false
use_ecg_founder: false

# embedding_size: 768
embedding_size: 1024
# encoder_type: transformer
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s","s","s"]
# xlstm_config: ['m','m','s','s','m','m','s','s','m','m','m']
# checkpoint: pretrain-xLSTM/bjtcbcpo/checkpoints/epoch=50-step=656472.ckpt 
# checkpoint: pretrain-xLSTM/y7gvl8tt/checkpoints/epoch=10-step=117260.ckpt
# patch_embedding: non_linear
patch_embedding: linear

use_final_layer_norm: false
bidirectional: true
cls_type: avg
num_reg_token: 0

monitor_metric: val_f1
monitor_mode: max

win_len: 3600
patch_size: 25
sampling_freq: 100
max_length_signal: 36

shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: false

use_scheduler: true
patience: 30
batch_size: 96
optimizer: 'adamw'
r_peaks_lambda: 0.
split_val_by_patient: true
clip_grad: 3.
num_epochs_warmup: 1

random_surrogate_prob: 0.
random_jitter_prob: 0.
random_drop_leads: 0.
random_crop: 1.
use_class_weights: true

layerwise_lr_decay: 0 #.75
drop_path_prob: 0.

data_folder_mit: /home/datasets/MIT-BIH_arrhythmia/
