# training loop hyp
wandb_log: true
epochs: 20
lr_head: .001
lr_xlstm: .00001
wd: 0.
dropout: 0.
linear_probing: false
task: multiclass
deterministic: false
batch_size: 128
num_workers: 64 

drop_path_prob: 0. # 0.5 # 0.5
layerwise_lr_decay: 0. # 0.75 # 0.75

use_ecg_founder: false
use_st_mem: false
use_ecg_jepa: false
grad_clip: 3.

sampling_freq: 100
patch_size: 25
optimizer: adamw

max_length_signal: 1200

# embedding_size: 768
embedding_size: 1024
# encoder_type: transformer
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s","s","s"]
# xlstm_config: ['m','m','s','s','m','m','s','s','m','m','m']
# checkpoint: pretrain-xLSTM/bjtcbcpo/checkpoints/epoch=50-step=656472.ckpt 
# checkpoint: pretrain-xLSTM/y7gvl8tt/checkpoints/epoch=10-step=117260.ckpt
# patch_embedding: non_linear
patch_embedding: linear

use_final_layer_norm: false
bidirectional: true
cls_type: avg
num_reg_token: 0
cls_normalization: batch #  batch # 'batch', 'layer', 'instance'


data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/
labels_file_mimic: /scratch/datasets/mimic-iv-ecg/raw/exams_filtered.csv
