window_size_train: 90000
window_size_val: 90000
max_length_signal: 90000

use_ecg_founder: false
# leads: ['II']
use_st_mem: false
use_ecg_jepa: false

# training loop hyp
wandb_log: true
epochs: 15
lr_head: .0001
lr_core: .0001
wd: 0.01
dropout: 0.
linear_probing: false
normalize: false
deterministic: false

# embedding_size: 768
embedding_size: 1024
# encoder_type: transformer
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s","s","s"]
# xlstm_config: ['m','m','s','s','m','m','s','s','m','m','m']
# checkpoint: pretrain-xLSTM/bjtcbcpo/checkpoints/epoch=50-step=656472.ckpt 
# checkpoint: pretrain-xLSTM/y7gvl8tt/checkpoints/epoch=10-step=117260.ckpt
# patch_embedding: non_linear
patch_embedding: linear

patch_size: 25
use_final_layer_norm: false
bidirectional: true
cls_type: avg

use_scheduler: true
num_epochs_warm_restart: 17
num_epochs_warmup: 3
patience: 5
batch_size: 3
optimizer: 'adamw'
grad_clip: 3.

sampling_freq: 100

use_class_weights: false

random_surrogate_prob: 0.
random_jitter_prob: 0.
random_drop_leads: 0.
random_resample: false
random_crop: 1.
normalize: false
nk_clean: false
shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: false


drop_path_prob:  0. #0.5
layerwise_lr_decay:  0. #0.75

# data_folder_sleep_apnea:  /home/datasets/sleep_apnea/physionet_apnea/
