wandb_log: true

lr_head: 0.0001
lr_xlstm: 0.0001
wd: 0.001
dropout: 0.1
random_shift: true

embedding_size: 1024
xlstm_type: "vanilla"
xlstm_config: [ 'm', 'm', 's', 's', 'm', 'm', 'm', 'm', 'm' ]
# checkpoint: pretrained_models/9l_1024/epoch=8-step=38070.ckpt
patch_embedding: enriched
bidirectional: true

win_len: 3600
patch_size: 64

use_start_token: true

use_scheduler: true
num_epochs_warm_restart: 30
patience: 30
batch_size: 64
optimizer: 'adamw'
r_peaks_lambda: 0. 
split_val_by_patient: true
use_focal_loss: false
clip_grad: 0.5