# training loop hyp
wandb_log: true
wandb_group: new_models
epochs: 50
lr_head: .001
lr_xlstm: .00001
wd: 0.1
dropout: 0.
linear_probing: false
task: multilabel
deterministic: true

use_ecg_founder: false
use_st_mem: false
use_ecg_jepa: false

# embedding_size: 1536
embedding_size: 1024
# encoder_type: transformer
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
# xlstm_config: ['m','m','s','s','m','m','s','s','m','m','m']
# checkpoint: pretrain-xLSTM/bjtcbcpo/checkpoints/epoch=50-step=656472.ckpt 
# checkpoint: pretrain-xLSTM/y7gvl8tt/checkpoints/epoch=10-step=117260.ckpt
# checkpoint: pretrain-xLSTM/yqi3smm8/checkpoints/epoch=41-step=1695792.ckpt
# checkpoint: pretrain-xLSTM/0rgc8fun/checkpoints/epoch=49-step=504700.ckpt
checkpoint: pretrain-xLSTM/nnv4heoe/checkpoints/epoch=16-step=343196.ckpt
patch_embedding: sparse_conv
#checkpoint: pretrain-xLSTM/1evs4ds0/checkpoints/epoch=49-step=95400.ckpt
#checkpoint: pretrain-xLSTM/y3odx16j/checkpoints/epoch=48-step=93492.ckpt
#checkpoint: pretrain-xLSTM/7mqchj8e/checkpoints/epoch=49-step=95400.ckpt
#checkpoint: pretrain-xLSTM/klkq3mwa/checkpoints/epoch=12-step=24804.ckpt
# checkpoint: pretrain-xLSTM/rt1elhpv/checkpoints/epoch=26-step=51516.ckpt
# checkpoint: pretrain-xLSTM/qz2978wl/checkpoints/epoch=49-step=95400.ckpt
#checkpoint:  pretrain-xLSTM/n0sw454t/checkpoints/epoch=42-step=82044.ckpt 
# checkpoint: pretrain-xLSTM/6r37lqvx/checkpoints/epoch=45-step=87768.ckpt 
# checkpoint: pretrain-xLSTM/19xebu64/checkpoints/epoch=49-step=95400.ckpt
# checkpoint: pretrain-xLSTM/j55tmgvb/checkpoints/epoch=45-step=592112.ckpt
# checkpoint:  pretrain-xLSTM/9sbsh80j/checkpoints/epoch=10-step=156332.ckpt
# checkpoint: pretrain-xLSTM/sslptfx3/checkpoints/epoch=12-step=138580.ckpt
# checkpoint: pretrain-xLSTM/r4qzaxee/checkpoints/epoch=11-step=154464.ckpt
# checkpoint: pretrain-xLSTM/b45usreq/checkpoints/epoch=12-step=17472.ckpt
# checkpoint:  pretrain-xLSTM/sqj0tg8j/checkpoints/epoch=44-step=60480.ckpt
# checkpoint: "pretrained_models/simdino/b45usreq/model.ckpt"
# patch_size: 50
patch_size: 25
use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'
bidirectional: true
cls_type: avg
# task: multiclass
num_reg_token: 0

#low_pass_filter: 30
#high_pass_filter: 0.5
use_scheduler: true
num_epochs_warmup: 1
patience: 20
monitor_metric: 'val_auroc'
monitor_mode: max
# batch_size: 96 #128
batch_size: 128
optimizer: adamw
grad_clip: 3.

sampling_freq: 100
# sampling_freq: 250
use_class_weights: true
use_focal_loss: false

random_surrogate_prob: 0.
random_jitter_prob: 0.
random_drop_leads: 0.
random_resample: false
random_crop: 1. # 0.9
normalize: false
nk_clean: false

shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: false
random_change_amplitude: 0.

classification_taksk: 'diagnosis_superclass'
num_classes: 5 # chenge to 23 if diagnosis_subclass

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/
labels_file_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/exams_filtered.csv

drop_path_prob: 0. # 0.75
layerwise_lr_decay: 0.75 # 0.75
training_pct: 1.
