# training loop hyp
wandb_log: false
wandb_group: test
epochs: 1
lr_head: .001
lr_core: .00001
wd: 0.01
dropout: 0.
linear_probing: true
task: multiclass
deterministic: true
batch_size: 512

drop_path_prob: 0.
layerwise_lr_decay: 1.

use_st_mem: false
use_ecg_jepa: false

sampling_freq: 100
patch_size: 25
optimizer: adamw

max_length_signal: 1200

embedding_size: 1024
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
checkpoint: pretrained_models/simdino/no_mimic_xlstm.ckpt

use_final_layer_norm: false
patch_embedding: linear
bidirectional: true
cls_type: avg
num_reg_token: 0

use_ecg_founder: false