# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_ft
wd: 0.001

lr_head: 0.03
lr_core: 0.03
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false

linear_probing: false
deterministic: false
cls_normalization: null

use_ecg_cpc: true

data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/

