# training loop hyp
wandb_log: true
wandb_group: best_jepa_lp
epochs: 20
wd: 0.1
batch_size: 512

lr_head: 0.003

linear_probing: true
deterministic: false

use_ecg_jepa: true

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/


training_pct: 1.
