# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_lp
wd: 0.001

lr_head: 0.1
lr_core: 0.1
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false
batch_size: 512

linear_probing: true
deterministic: false
training_dataset: ['code15']

use_ecg_cpc: true

data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/
labels_file_mimic: /scratch/datasets/mimic-iv-ecg/raw/exams_filtered.csv
data_folder_code15: /scratch/datasets/CODE15/processed/
labels_file_code15: /scratch/datasets/CODE15/processed/exams_filtered.csv