# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_ft
epochs: 30
wd: 0.001
batch_size: 256

lr_head: 0.03
lr_core: 0.03
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false

linear_probing: false
deterministic: false
cls_normalization: null

use_ecg_cpc: true

data_folder_cpsc2018: /home/datasets/CPSC2018/


training_pct: 1.
normalize: false

max_length_signal: 2400