# training loop hyp
wandb_log: true
wandb_group: best_xlstm_sup
epochs: 30
wd: 0.1
batch_size: 128

lr_head: 0.0001
lr_core: 0.0001
drop_path_prob: 0.
layerwise_lr_decay: 0.

linear_probing: false
deterministic: false

embedding_size: 1024
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
# checkpoint: pretrain-xLSTM/0rgc8fun/checkpoints/epoch=49-step=504700.ckpt
cls_type: max

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_cpsc2018: /home/datasets/CPSC2018/


max_length_signal: 5000

training_pct: 1.
